---
- name: test if atom_apm_packages is set correctly
  assert:
    that:
      - atom_apm_packages | length > 0
      - atom_apm_packages is iterable
    quiet: yes
  when:
    - atom_apm_packages is defined
