---
# tasks file for atom
- name: include assert.yml
  include_tasks: assert.yml

- name: install requirements
  package:
    name: "{{ atom_requirements }}"
    state: present
  when:
    - atom_requirements is defined
    - ansible_pkg_mgr == "apt"
  register: atom_install_requirements
  until: atom_install_requirements is succeeded
  retries: 3

- name: download atom
  get_url:
    url: "{{ atom_package_url }}"
    dest: "/tmp/{{ atom_package }}"
    checksum: "{{ atom_checksum }}"
    validate_certs: no
  when:
    - ansible_pkg_mgr == "apt" or
      ansible_pkg_mgr == "dnf" or
      ansible_pkg_mgr == "yum" or
      ansible_pkg_mgr == "zypper"
  register: atom_download_atom
  until: atom_download_atom is succeeded
  retries: 3

- name: install atom deb
  apt:
    deb: "/tmp/{{ atom_package }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"
  register: atom_intall_atom_deb
  until: atom_intall_atom_deb is succeeded
  retries: 3

- name: install atom rpm dnf
  dnf:
    name: "/tmp/{{ atom_package }}"
    state: present
  when:
    - ansible_pkg_mgr == "dnf"
  register: atom_install_atom_rpm_dnf
  until: atom_install_atom_rpm_dnf is succeeded
  retries: 3

- name: install atom rpm yum
  yum:
    name: "/tmp/{{ atom_package }}"
    state: present
  when:
    - ansible_pkg_mgr == "yum"
  register: atom_install_atom_rpm_yum
  until: atom_install_atom_rpm_yum is succeeded
  retries: 3

- name: install atom rpm zypper
  zypper:
    name: "/tmp/{{ atom_package }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr == "zypper"
  register: atom_install_atom_rpm_zypper
  until: atom_install_atom_rpm_zypper is succeeded
  retries: 3

- name: install apm packages
  command: apm install {{ item }}
  args:
    creates: /root/.atom/packages/linter
  loop: "{{ atom_apm_packages }}"
  register: atom_install_apm_packages
  until: atom_install_apm_packages is succeeded
  retries: 3
