---
# tasks file for atom
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install requirements
  package:
    name: "{{ atom_requirements }}"
    state: present
  when:
    - atom_requirements is defined
    - ansible_pkg_mgr == "apt"

- name: download atom
  get_url:
    url: "{{ atom_package_url }}"
    dest: "/tmp/{{ atom_package }}"
    checksum: "{{ atom_checksum }}"
    validate_certs: no
  when:
    - ansible_pkg_mgr == "apt" or
      ansible_pkg_mgr == "dnf" or
      ansible_pkg_mgr == "yum" or
      ansible_pkg_mgr == "zypper"

- name: install atom deb
  apt:
    deb: "/tmp/{{ atom_package }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: install atom rpm dnf
  dnf:
    name: "/tmp/{{ atom_package }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr == "dnf"

- name: install atom rpm yum
  yum:
    name: "/tmp/{{ atom_package }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr == "yum"

- name: install atom rpm zypper
  zypper:
    name: "/tmp/{{ atom_package }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr == "zypper"

- name: install apm packages
  command: apm install {{ item }}
  args:
    creates: /root/.atom/packages/linter
  loop: "{{ atom_apm_packages }}"
